language: ruby
rvm: 2.4.2
cache:
  bundler: true
  yarn: true
addons:
  postgresql: '9.6'
services:
- postgresql
install:
- bin/yarn
- bin/bundle
before_script:
- bin/dotenv -f .env.test bin/rails db:setup
- bin/webpack
deploy:
  provider: heroku
  app:
    primary: nourish-party
  api_key:
    secure: UT2xMjJ8lyeYj7pUZAfjNHTZ5AeZPIJqQrXm2KEMNwRkHwgaHtMeZNghI0vzRwQG1VgOYxklqJNJMaLXNFLkaVEqPueM7wJ+UGPHKu6PUBhlhIDw1UTtXgg8cTTiSylVQBILbTAORO6NMd0p7bjbcPNbLKBh4Ku8PtEw9zsYR+UocrIllAj2u+EtZ0W221WRSWc9UomzGF4pjQOJiE/X/Wz7djZQKLAnnr9Jcb+g2D/QenoNasRU+zyeM5b7uTEZhcCiL1Bf1AehYlhm8RfecoRmuLQWbbNM0VvNpU67BUH2rol1qOF9Af8bcGP9s/0MujPqoHO8L75GfXAp4WQAXGE0HxdUW8yFONs8cXrEg3/ExWHEOzJNGX4KMFGy0jA7rFEzPNOnnd8D60st3qwhDWwjYFdglwFjTFc3dOpYW4gEITrdRu7RpJnJ+c9R21yFnhVK/wE4zgiplEBYS6Yngaamg3wu799DM3jcS1aYngnQEHzcLAtBhaAJG4bQaWoOMtw9UGgYdtGNtu2HDqmF6edmj6M0PhFJpyjC+QnRjHJw4UfmZ6phPQ7MDjUgB2RzdOtURFfr15K3QwJhit0VepFuKfHmE+mimAwf8JE1Exz9TnfKsKfQFLD+GU3QCMAnpgAl1mBTJ0216eKdcAMeF85pqfvlyYJzqshPClbCdwE=
  run:
  - rake db:migrate
  - restart
