language: ruby
rvm: 2.4.2
before_install:
  - psql -c 'create database nourish_party_test;' -U postgres
  - psql nourish_party_test -c 'CREATE EXTENSION "uuid-ossp";' -U postgres
  - psql nourish_party_test -c 'CREATE EXTENSION "pgcrypto";' -U postgres
services:
  - postgresql
before_script:
  - bin/rails db:setup
