language: ruby
rvm: 2.4.2
cache:
  bundler: true
  yarn: true
addons:
  postgresql: "9.6"
services:
  - postgresql
install:
  - bin/yarn
  - bin/bundle
before_script:
  - bin/rails db:setup
  - bin/webpack
