require_relative "moderation/moderator_action_form_section"
require_relative "moderation/moderator_action_section"
require_relative "moderation/pending_project_section"

require_relative "moderation/pending_projects_page"
require_relative "moderation/moderator_actions_page"
